package com.wts.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComplainletter<M extends BaseComplainletter<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 人员姓名
	 */
	public void setPersonName(java.lang.String PersonName) {
		set("PersonName", PersonName);
	}
	
	/**
	 * 人员姓名
	 */
	public java.lang.String getPersonName() {
		return getStr("PersonName");
	}

	/**
	 * 证件号码
	 */
	public void setPersonNumber(java.lang.String PersonNumber) {
		set("PersonNumber", PersonNumber);
	}
	
	/**
	 * 证件号码
	 */
	public java.lang.String getPersonNumber() {
		return getStr("PersonNumber");
	}

	/**
	 * 人员性别
	 */
	public void setPersonSex(java.lang.String PersonSex) {
		set("PersonSex", PersonSex);
	}
	
	/**
	 * 人员性别
	 */
	public java.lang.String getPersonSex() {
		return getStr("PersonSex");
	}

	/**
	 * 联系电话
	 */
	public void setPersonPhone(java.lang.String PersonPhone) {
		set("PersonPhone", PersonPhone);
	}
	
	/**
	 * 联系电话
	 */
	public java.lang.String getPersonPhone() {
		return getStr("PersonPhone");
	}

	/**
	 * 家庭住址
	 */
	public void setPersonAddress(java.lang.String PersonAddress) {
		set("PersonAddress", PersonAddress);
	}
	
	/**
	 * 家庭住址
	 */
	public java.lang.String getPersonAddress() {
		return getStr("PersonAddress");
	}

	/**
	 * 投诉时间
	 */
	public void setComplaintDate(java.util.Date ComplaintDate) {
		set("ComplaintDate", ComplaintDate);
	}
	
	/**
	 * 投诉时间
	 */
	public java.util.Date getComplaintDate() {
		return get("ComplaintDate");
	}

	/**
	 * 公司名称
	 */
	public void setCompanyName(java.lang.String CompanyName) {
		set("CompanyName", CompanyName);
	}
	
	/**
	 * 公司名称
	 */
	public java.lang.String getCompanyName() {
		return getStr("CompanyName");
	}

	/**
	 * 公司地址
	 */
	public void setCompanyAddress(java.lang.String CompanyAddress) {
		set("CompanyAddress", CompanyAddress);
	}
	
	/**
	 * 公司地址
	 */
	public java.lang.String getCompanyAddress() {
		return getStr("CompanyAddress");
	}

	/**
	 * 法人姓名
	 */
	public void setLegalName(java.lang.String LegalName) {
		set("LegalName", LegalName);
	}
	
	/**
	 * 法人姓名
	 */
	public java.lang.String getLegalName() {
		return getStr("LegalName");
	}

	/**
	 * 法人职务
	 */
	public void setLegalPosition(java.lang.String LegalPosition) {
		set("LegalPosition", LegalPosition);
	}
	
	/**
	 * 法人职务
	 */
	public java.lang.String getLegalPosition() {
		return getStr("LegalPosition");
	}

	/**
	 * 法人电话
	 */
	public void setLegalPhone(java.lang.String LegalPhone) {
		set("LegalPhone", LegalPhone);
	}
	
	/**
	 * 法人电话
	 */
	public java.lang.String getLegalPhone() {
		return getStr("LegalPhone");
	}

	/**
	 * 人事姓名
	 */
	public void setPersonnelName(java.lang.String PersonnelName) {
		set("PersonnelName", PersonnelName);
	}
	
	/**
	 * 人事姓名
	 */
	public java.lang.String getPersonnelName() {
		return getStr("PersonnelName");
	}

	/**
	 * 人事电话
	 */
	public void setPersonnelPhone(java.lang.String PersonnelPhone) {
		set("PersonnelPhone", PersonnelPhone);
	}
	
	/**
	 * 人事电话
	 */
	public java.lang.String getPersonnelPhone() {
		return getStr("PersonnelPhone");
	}

	/**
	 * 诉求事项
	 */
	public void setAppealMatter(java.lang.String AppealMatter) {
		set("AppealMatter", AppealMatter);
	}
	
	/**
	 * 诉求事项
	 */
	public java.lang.String getAppealMatter() {
		return getStr("AppealMatter");
	}

	/**
	 * 事实理由
	 */
	public void setFactReason(java.lang.String FactReason) {
		set("FactReason", FactReason);
	}
	
	/**
	 * 事实理由
	 */
	public java.lang.String getFactReason() {
		return getStr("FactReason");
	}

}
