package com.wts.entity.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFilingcase<M extends BaseFilingcase<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public void setId(Integer id) {
		set("id", id);
	}
	
	/**
	 * 序号
	 */
	public Integer getId() {
		return getInt("id");
	}

	/**
	 * 人员姓名
	 */
	public void setPersonName(String PersonName) {
		set("PersonName", PersonName);
	}
	
	/**
	 * 人员姓名
	 */
	public String getPersonName() {
		return getStr("PersonName");
	}

	/**
	 * 证件号码
	 */
	public void setPersonNumber(String PersonNumber) {
		set("PersonNumber", PersonNumber);
	}
	
	/**
	 * 证件号码
	 */
	public String getPersonNumber() {
		return getStr("PersonNumber");
	}

	/**
	 * 当前年龄
	 */
	public void setPersonAge(String PersonAge) {
		set("PersonAge", PersonAge);
	}
	
	/**
	 * 当前年龄
	 */
	public String getPersonAge() {
		return getStr("PersonAge");
	}

	/**
	 * 人员性别
	 */
	public void setPersonSex(String PersonSex) {
		set("PersonSex", PersonSex);
	}

	/**
	 * 人员性别
	 */
	public String getPersonSex() {
		return getStr("PersonSex");
	}

	/**
	 * 联系电话
	 */
	public void setPersonPhone(String PersonPhone) {
		set("PersonPhone", PersonPhone);
	}
	
	/**
	 * 联系电话
	 */
	public String getPersonPhone() {
		return getStr("PersonPhone");
	}

	/**
	 * 家庭住址
	 */
	public void setPersonAddress(String PersonAddress) {
		set("PersonAddress", PersonAddress);
	}
	
	/**
	 * 家庭住址
	 */
	public String getPersonAddress() {
		return getStr("PersonAddress");
	}

	/**
	 * 投诉时间
	 */
	public void setComplaintDate(java.util.Date ComplaintDate) {
		set("ComplaintDate", ComplaintDate);
	}
	
	/**
	 * 投诉时间
	 */
	public java.util.Date getComplaintDate() {
		return get("ComplaintDate");
	}

	/**
	 * 公司名称
	 */
	public void setCompanyName(String CompanyName) {
		set("CompanyName", CompanyName);
	}
	
	/**
	 * 公司名称
	 */
	public String getCompanyName() {
		return getStr("CompanyName");
	}

	/**
	 * 公司地址
	 */
	public void setCompanyAddress(String CompanyAddress) {
		set("CompanyAddress", CompanyAddress);
	}
	
	/**
	 * 公司地址
	 */
	public String getCompanyAddress() {
		return getStr("CompanyAddress");
	}

	/**
	 * 法人姓名
	 */
	public void setLegalName(String LegalName) {
		set("LegalName", LegalName);
	}
	
	/**
	 * 法人姓名
	 */
	public String getLegalName() {
		return getStr("LegalName");
	}

	/**
	 * 法人职务
	 */
	public void setLegalPosition(String LegalPosition) {
		set("LegalPosition", LegalPosition);
	}
	
	/**
	 * 法人职务
	 */
	public String getLegalPosition() {
		return getStr("LegalPosition");
	}

	/**
	 * 法人电话
	 */
	public void setLegalPhone(String LegalPhone) {
		set("LegalPhone", LegalPhone);
	}
	
	/**
	 * 法人电话
	 */
	public String getLegalPhone() {
		return getStr("LegalPhone");
	}

	/**
	 * 人事姓名
	 */
	public void setPersonnelName(String PersonnelName) {
		set("PersonnelName", PersonnelName);
	}
	
	/**
	 * 人事姓名
	 */
	public String getPersonnelName() {
		return getStr("PersonnelName");
	}

	/**
	 * 人事电话
	 */
	public void setPersonnelPhone(String PersonnelPhone) {
		set("PersonnelPhone", PersonnelPhone);
	}
	
	/**
	 * 人事电话
	 */
	public String getPersonnelPhone() {
		return getStr("PersonnelPhone");
	}

	/**
	 * 诉求事项
	 */
	public void setAppealMatter(String AppealMatter) {
		set("AppealMatter", AppealMatter);
	}
	
	/**
	 * 诉求事项
	 */
	public String getAppealMatter() {
		return getStr("AppealMatter");
	}

	/**
	 * 事实理由
	 */
	public void setFactReason(String FactReason) {
		set("FactReason", FactReason);
	}
	
	/**
	 * 事实理由
	 */
	public String getFactReason() {
		return getStr("FactReason");
	}

}
