import baseUrl from '../../components/Common/Base'
export const base = baseUrl + '/api/file'
export const query = `${base}/query`
export const total = `${base}/total`
export const queryFlow = baseUrl + '/api/flow/query'
export const totalFlow = baseUrl + '/api/flow/total'
export const getFlow = baseUrl + '/api/flow/get'
export const editFlow = baseUrl + '/api/flow/edit'
export const printIn = baseUrl + '/api/flow/printIn'
export const printOut = baseUrl + '/api/flow/printOut'
export const printBorrow = baseUrl + '/api/flow/printBorrow'
export const add = `${base}/add`
export const edit = `${base}/edit`
export const get = `${base}/get`
export const borrow = `${base}/borrow`
export const back = `${base}/back`
export const out = `${base}/out`
export const resave = `${base}/resave`
export const getUser = `${base}/getUser`
export const check = `${base}/check`
export const resaveother = `${base}/resaveOther`
