package com.wts.entity.model;

import com.wts.entity.base.BaseComplainletter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Complainletter extends BaseComplainletter<Complainletter> {
	
}
