package com.wts.entity.model;

import com.wts.entity.base.BaseComplaintletter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Filingcase extends BaseComplaintletter<Filingcase> {
	
}
